name: FDA Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: "55 7 2 9 *"
  workflow_dispatch:   

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm run scrape
